[tool.poetry]
name = 'FRONT-INIT'
version = '0.1.0'
description = ''
authors = ['kylymnyk alina <kylymnykalina@gmail.com>']

[tool.poetry.dependencies]
python = '^3.10'
jinja2 = '^3.1.2'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"